package Yawner::Compiler::Batch;

use strict;
use warnings;
use Data::Dumper;

use Yawner::Util::Logger;

use Exporter qw(import);
our @EXPORT = qw(compile);

my $header = <<EOF;
\@echo off
rem This file has been generated by Yawner Batch Compiler

EOF

my $logger = Yawner::Util::Logger->new('compiler/batch');

my %CommandTable = (
    echo => 'echo'
);

my %escapes = (
    '%' => '%%',
    '^' => '^^',
    '&' => '^&',
    '|' => '^|',
    '>' => '^>',
    '<' => '^<'
);

sub escape {
    my $str = shift;
    $str =~ s/\Q$_\E/$escapes{$_}/g foreach keys %escapes;
    return $str;
}

sub process_node {
    my $node = shift;
    my $result = '';

    if($node->name eq 'Yawner::Lang::AST::LiteralValueNode'){
        $result = escape($node->value); 
    }elsif($node->name eq 'Yawner::Lang::AST::ExpandableValueNode'){
        $result = escape($node->value) =~ s/\$(\w+)/%$1%/gr; 
    }elsif($node->name eq 'Yawner::Lang::AST::CommandNode'){
        if($node->cmd eq 'echo'){
            $result .= 'echo(';   
        }else{
            $result .= $CommandTable{$node->cmd} . ' ';
        }

        foreach(@{$node->args}){
            $result .= process_node($_) . ' ';
        }
    }elsif($node->name eq 'Yawner::Lang::AST::VariableDefinitionNode'){
        if($node->value->name eq 'Yawner::Lang::AST::LiteralValueNode' || $node->value->name eq 'Yawner::Lang::AST::ExpandableValueNode'){
            $result .= 'set "' . $node->var . '=' . process_node($node->value) . '"';
        }else{
            $logger->error("Unsupported feature: only literal and expandable values can be assigned to a variable (at " . $node->line . ':' . $node->char . ')'); 
            die;
        }
    }

    return $result;
}

sub compile {
    my @ast = @_;
    my $result = $header;

    foreach(@ast){
        $result .= process_node($_) . "\n";
    }

    return $result;
}
