package Yawner::Compiler::Batch;

use strict;
use warnings;

use Exporter qw(import);
our @EXPORT = qw(compile);

my $header = <<EOF;
\@echo off
rem This file has been generated by Yawner Batch Compiler

EOF

sub compile {
    my @ast = @_;
    my $result = $header;

    foreach my $node (@ast){
        if($node->name eq 'Yawner::Lang::AST::CommandNode'){
            if($node->cmd eq 'echo'){
                $result .= 'echo(';

                foreach(@{$node->args}){
                    $result .= $_->value;
                }
            }else{
                $result .= $node->cmd . ' ';

                foreach(${$node->args}){
                    $result .=  '"' . $_->value . '"';
                }
            }
        }
    }

    return $result;
}
