package Yawner::Compiler::Shell;

use strict;
use warnings;
use Data::Dumper;

use Exporter qw(import);
our @EXPORT = qw(compile);

my $header = <<EOF;
#!/usr/bin/env sh
# This file has been generated by Yawner Unix-Shell Compiler

EOF

my %CommandTable = (
    echo => 'echo'
);

sub process_node {
    my $node = shift;
    my $result = '';

    if($node->name eq 'Yawner::Lang::AST::LiteralValueNode'){
        $result = '\'' . $node->value . '\''; 
    }elsif($node->name eq 'Yawner::Lang::AST::ExpandableValueNode'){
        $result = '"' . $node->value . '"';
    }elsif($node->name eq 'Yawner::Lang::AST::CommandNode'){
        $result .= $CommandTable{$node->cmd} . ' ';

        foreach(@{$node->args}){
            $result .= process_node($_) . ' ';
        }
    }elsif($node->name eq 'Yawner::Lang::AST::VariableDefinitionNode'){
        $result .= $node->var . '=' . process_node($node->value);
    }

    return $result;
}

sub compile {
    my @ast = @_;
    my $result = $header;

    foreach(@ast){
        $result .= process_node($_) . "\n";
    }

    return $result;
}
