package Yawner::Compiler::Shell;

use strict;
use warnings;
use Data::Dumper;

use Exporter qw(import);
our @EXPORT = qw(compile);

my $header = <<EOF;
#!/usr/bin/env sh
# This file has been generated by Yawner Unix-Shell Compiler

EOF

my %CommandTable = (
    echo => 'echo'
);

sub compile {
    my @ast = @_;
    my $result = $header;

    foreach my $node (@ast){
        if($node->name eq 'Yawner::Lang::AST::CommandNode'){
            $result .= $CommandTable{$node->cmd} . ' ';

            foreach(@{$node->args}){
                $result .= '\'' . $_->value . '\'';
            }
        }
    }

    return $result;
}
